CREATE PROCEDURE BuscaPorEntidades @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
		SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
		SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE VENDEDORES]
END

EXEC BuscaPorEntidades @ENTIDADE = 'CLIENTES'
EXEC BuscaPorEntidades @ENTIDADE = 'VENDEDORES' 

-- EXERCICIO --
CREATE PROCEDURE BuscaPorEntidadesCompleta @ENTIDADE2 AS VARCHAR(10)
AS 
BEGIN 
	IF @ENTIDADE2 = 'PRODUTOS'
		SELECT [CODIGO DO PRODUTO] AS IDENTIFICADOR, [CODIGO DO PRODUTO]  AS DESCRITOR
		FROM [TABELA DE PRODUTOS]
END

EXEC BuscaPorEntidadesCompleta @ENTIDADE2 = 'PRODUTOS' 