DECLARE @NOME VARCHAR (200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 [nome] FROM [TABELA DE CLIENTES] tdc 
OPEN CURSOR1 
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT @NOME 
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

----------------------------------------------------------------------------------

DECLARE @NOME VARCHAR (200)
DECLARE @ENDERECO VARCHAR (MAX)
DECLARE CURSOR3 CURSOR FOR 
SELECT NOME, ([ENDERECO 1] + ' - ' + BAIRRO + ' - '  + CIDADE + ' - ' + ESTADO + ' - ' + CEP) END_COMPLETO
FROM [TABELA DE CLIENTES] tdc  
OPEN CURSOR3 
FETCH NEXT FROM CURSOR3 INTO  @NOME, @ENDERECO 
WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT @NOME + ' Endereco: ' + @ENDERECO
	FETCH NEXT FROM CURSOR3 INTO @NOME, @ENDERECO
END



