SELECT tdc.CPF , tdc.NOME, SUM(inf.[QUANTIDADE] * inf.[PREÇO]) AS FATURAMENTO,
SUM(inf.[QUANTIDADE] * inf.[PREÇO]) / 10 AS COMISSAO
FROM [TABELA DE CLIENTES] tdc INNER JOIN [NOTAS FISCAIS] nf ON tdc.CPF = nf.CPF 
INNER JOIN [ITENS NOTAS FISCAIS] inf ON inf.NUMERO = nf.NUMERO 
WHERE tdc.CPF = '1471156710' AND YEAR(nf.[DATA]) = 2016
GROUP BY tdc.CPF , tdc.NOME 
-----------------------------------------------------------------------------

DECLARE @DENOMINADOR INT
SET @DENOMINADOR = 0  --- Neste caso, se o denominador for = 0, 
--------------------------teremos um erro ao tentar fazer uma divisão por zero

SELECT tdc.CPF , tdc.NOME, SUM(inf.[QUANTIDADE] * inf.[PREÇO]) AS FATURAMENTO,
SUM(inf.[QUANTIDADE] * inf.[PREÇO])/@DENOMINADOR AS COMISSAO
FROM [TABELA DE CLIENTES] tdc INNER JOIN [NOTAS FISCAIS] nf ON tdc.CPF = nf.CPF 
INNER JOIN [ITENS NOTAS FISCAIS] inf ON inf.NUMERO = nf.NUMERO 
WHERE tdc.CPF = '1471156710' AND YEAR(nf.[DATA]) = 2016
GROUP BY tdc.CPF , tdc.NOME

--------------------------------------------------------------------------------
CREATE PROCEDURE TrataErroZero
@CPF VARCHAR (12), @ANO INT, @DENOMINADOR INT, @NUMERRO INT OUTPUT, @NUMLINHA INT OUTPUT
AS
BEGIN 
	SELECT tdc.CPF , tdc.NOME, SUM(inf.[QUANTIDADE] * inf.[PREÇO]) AS FATURAMENTO,
	SUM(inf.[QUANTIDADE] * inf.[PREÇO])/@DENOMINADOR AS COMISSAO
	FROM [TABELA DE CLIENTES] tdc INNER JOIN [NOTAS FISCAIS] nf ON tdc.CPF = nf.CPF 
	INNER JOIN [ITENS NOTAS FISCAIS] inf ON inf.NUMERO = nf.NUMERO 
	WHERE tdc.CPF = @CPF AND YEAR(nf.[DATA]) = @ANO
	GROUP BY tdc.CPF , tdc.NOME
	SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @CPF VARCHAR (12)
DECLARE @ANO INT
DECLARE @DENOMINADOR INT
DECLARE @NUMERRO INT 
DECLARE @NUMLINHA INT 
SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
EXEC TrataErroZero @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR, 
@NUMERRO = @NUMERRO OUTPUT, @NUMLINHA = @NUMLINHA OUTPUT
IF @NUMERRO <> 0
	PRINT ('Houve um Erro' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA))




